In [140]:
import numpy as np


In [141]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [142]:
a=[1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [143]:
a=np.array(a)
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [144]:
a=[1,2,3.5]
a

[1, 2, 3.5]

In [145]:
arr=np.array(a)
arr


array([1. , 2. , 3.5])

In [146]:
s=[[1,2,3],[4,5,6],[7,8,9]]
print(s)
print(type(s))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [147]:
#one diamensional and two siamensional ka uper tensor hota ha  
arr=np.array(s)
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


Array generation function

In [148]:
# arange fun range ki taraha hi work karta ha jis taraha hum4
#  python ma work kartatha start stop step


arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [149]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [150]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [151]:
arr=np.ones((4,6)) # horizontal are row and vertical are column
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [152]:
# linear  spacing =Return evenly space number over a specified interval

arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation Functiion

In [153]:
# 0 to 1 range ka beech ma value lie kar rahi ha vo normalization khata ha 
# -3 to 3 ka beech lie karrahi ha usha  standardization khata ha 

arr=np.random.rand(2)
print(arr)

[0.49652954 0.67269539]


In [154]:
np.random.randn(15)

array([ 0.33140427,  0.13523966, -1.19704712, -1.54543169, -0.56731786,
        0.09845344,  0.03328746, -1.09522854, -0.39638392,  1.23025547,
       -0.35315863, -0.34935269, -0.35156148,  1.07131973, -0.04142257])

In [155]:
# randint ma low and highest point and size
np.random.randint(10,20,10)

array([12, 13, 19, 14, 16, 10, 12, 15, 19, 10])

Array  Attributes

Attributes = Reprsent the data or properties of an object 
 ex : attributes ko calll nahi kiya jata 

method= Represent the behavior and action of an obj
ex: Method ko call kiya jata ha 


In [156]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
arr.shape

(3, 3)

In [158]:
arr.size

9

In [159]:
arr.dtype

dtype('int32')

Array Method

In [160]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr.min()

1

In [162]:
arr.max()

9

In [163]:
arr.sum()

45

In [164]:
# np.sum(arr,axis)
np.sum(arr,axis=0)

array([12, 15, 18])

In [165]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [166]:
arr.mean()

5.0

In [167]:
arr.std()

2.581988897471611

In [168]:
arr.argmax()

8

In [169]:
arr.argmin()

0

Reshaping And Resizing


In [170]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [171]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [172]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Array indexing 

Numpy indexing and slicing of vector

In [173]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [174]:
arr[9]

20

In [175]:
arr[1:5]

array([12, 13, 14, 15])

In [176]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

Numpy indexing and slicing of Matrix

In [177]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

INdexing

In [178]:
arr[5,4]

30

Slicing

In [179]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [180]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [181]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [182]:
arr[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

Boolean Indexing

In [183]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [184]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [185]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Arrray operation

Arthmetic operation

In [186]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [187]:
a2-a1

array([5, 5, 5, 5, 5])

In [188]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [189]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Broadcasting

In [190]:
l=[10,20,30,40,50]
arr=np.array(l)
arr+10

array([20, 30, 40, 50, 60])

In [191]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [192]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Shallo copy and Deepcopy

In [193]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [194]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [195]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [196]:
a[4:6]*10

array([50, 60])

In [197]:
a
b=a.copy()
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [198]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operation

In [199]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat1

array([[1, 2],
       [3, 4]])

In [200]:
mat2

array([[5, 6],
       [7, 8]])

In [201]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [202]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [203]:
mat1

array([[1, 2],
       [3, 4]])

In [204]:
mat1.T

array([[1, 3],
       [2, 4]])

Advance array manipulation


Stacking Array

In [205]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [206]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [207]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [209]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [211]:
a=np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [212]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


Exercise  

In [213]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [214]:
s.sum()

405

In [215]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [216]:
for i in b:
    if i!=45:
        print("Not valid")
        break
else:
    print("valid")

valid


In [217]:
c=np.sum(s,axis=1)
for i in c:
    if i!=45:
        print("Not valid")
        break
else:
    print("valid")

valid


In [218]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())
    



45
45
45
45
45
45
45
45
45


In [219]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [220]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [221]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

Problem solve

In [222]:
# column :[Age,Math,Marks,Science Marks]
data=np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [20,90,85]
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [20, 90, 85]])

In [223]:
data.shape

(4, 3)

In [224]:
# find the avg age of students
np.mean(data[:,0:1])

18.5

In [225]:
# Extract math marks of all student

data[:,1]

array([85, 92, 76, 90])

In [226]:
# Find the highest science marks
np.max(data[:,2])

95

In [227]:
# Get details of the student who scored more than 90 marks
data[data[:,1]>90]

array([[19, 92, 88]])

In [228]:
# Increase maths marks of student + 5
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [231]:
# find how many student younger thann 19
len(data[data[:,0] < 19])


2

In [ ]:
# calculate the avg marks of each subject(colun axis=0)

np.mean(data[:,1:],axis=0)

array([90.75, 86.5 ])

In [241]:
# get data of student who scored at leat 80 in both subject
data[(data[:,1] >=80) & (data[:,2]>=80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [249]:
# replace all science marks <75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])