In [4]:
! pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
b=np.array([1,2,3,4])

In [7]:
b.shape

(4,)

In [8]:
b.ndim

1

In [9]:
b

array([1, 2, 3, 4])

In [13]:
c=np.array([[[1,2,3],[53,7,5],[5,7,5]]])


In [14]:
c.shape

(1, 3, 3)

In [15]:
c.ndim

3

In [16]:
c

array([[[ 1,  2,  3],
        [53,  7,  5],
        [ 5,  7,  5]]])

In [21]:
np.arange(1,10,dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
np.arange(1,10,dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [27]:
np.linspace(1,100,num=30,dtype=int)

array([  1,   4,   7,  11,  14,  18,  21,  24,  28,  31,  35,  38,  41,
        45,  48,  52,  55,  59,  62,  65,  69,  72,  76,  79,  82,  86,
        89,  93,  96, 100])

In [28]:
np.linspace(1,100,dtype=int)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [31]:
len(c)

1

In [39]:
arr1=np.linspace(1,100,num=30,dtype=int)

In [40]:
len(arr1)

30

In [42]:
arr1.reshape(5,6)

array([[  1,   4,   7,  11,  14,  18],
       [ 21,  24,  28,  31,  35,  38],
       [ 41,  45,  48,  52,  55,  59],
       [ 62,  65,  69,  72,  76,  79],
       [ 82,  86,  89,  93,  96, 100]])

In [44]:
b=np.array([[1,2,3],[5,7,5]])

In [45]:
b.ndim

2

In [49]:
b.size

6

In [46]:
len(b)

2

In [47]:
b.shape

(2, 3)

In [48]:
c=np.array([[[1,2,3],[53,7,5],[5,7,5]]])

In [53]:
array4=np.linspace(1,16,num=16)
array4.reshape(4,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [54]:
array4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [62]:
array5=np.linspace(1,60,num=16,dtype=int)
array5.reshape(4,4)


array([[ 1,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60]])

In [63]:
array5=np.arange(1,17)

In [66]:
array5.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

RANK
MATRIX OPERATION

import numpy as np
np.linespace(12,50,num=25,)

In [51]:
x=np.linspace(12,50,num=25).reshape(5,5)

# print(x)
x,

(array([[12.        , 13.58333333, 15.16666667, 16.75      , 18.33333333],
        [19.91666667, 21.5       , 23.08333333, 24.66666667, 26.25      ],
        [27.83333333, 29.41666667, 31.        , 32.58333333, 34.16666667],
        [35.75      , 37.33333333, 38.91666667, 40.5       , 42.08333333],
        [43.66666667, 45.25      , 46.83333333, 48.41666667, 50.        ]]),)

In [3]:
# rankofthe  matrix

np.linalg.matrix_rank(x)

NameError: name 'np' is not defined

In [53]:
np.linalg.eigvals(x)

array([ 1.58943146e+02, -3.94314650e+00, -9.02568202e-15,  4.95296857e-15,
        9.20545154e-15])

In [54]:
np.linalg.eig(x)

EigResult(eigenvalues=array([ 1.58943146e+02, -3.94314650e+00, -9.02568202e-15,  4.95296857e-15,
        9.20545154e-15]), eigenvectors=array([[-0.21171745,  0.66231591, -0.61218952, -0.11298241,  0.05581438],
       [-0.31676699,  0.34686975,  0.49747503, -0.35999754, -0.03968199],
       [-0.42181653,  0.03142359,  0.51560897,  0.87965271,  0.35706058],
       [-0.52686607, -0.28402257, -0.07488494, -0.22738317, -0.81833272],
       [-0.63191561, -0.59946873, -0.32600954, -0.17928959,  0.44513975]]))

In [55]:
eigon_value,eigen_vector=np.linalg.eig(x)
eigen_vector
# eigon_value

array([[-0.21171745,  0.66231591, -0.61218952, -0.11298241,  0.05581438],
       [-0.31676699,  0.34686975,  0.49747503, -0.35999754, -0.03968199],
       [-0.42181653,  0.03142359,  0.51560897,  0.87965271,  0.35706058],
       [-0.52686607, -0.28402257, -0.07488494, -0.22738317, -0.81833272],
       [-0.63191561, -0.59946873, -0.32600954, -0.17928959,  0.44513975]])

DETERMINANT 
Scaling factor to measure  and find the rotation and sharering we use determinant 
 


In [ ]:
# deterinant 
np.linalg.det(x)

np.float64(0.0)

In [ ]:
# inverse
np.linalg.inv(x)

LinAlgError: Singular matrix

In [58]:
# tranpose matrix
np.linalg.matrix_transpose(x)

array([[12.        , 19.91666667, 27.83333333, 35.75      , 43.66666667],
       [13.58333333, 21.5       , 29.41666667, 37.33333333, 45.25      ],
       [15.16666667, 23.08333333, 31.        , 38.91666667, 46.83333333],
       [16.75      , 24.66666667, 32.58333333, 40.5       , 48.41666667],
       [18.33333333, 26.25      , 34.16666667, 42.08333333, 50.        ]])

In [65]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[4,5,6],[1,2,3]])

In [66]:
# multiplr two matrix
np.dot(a,b)

array([[ 20,  24,  28],
       [ 62,  69,  76],
       [104, 114, 124]])

In [ ]:
np.cross(a,b) #cross product of two matrix

array([[-10,  20, -10],
       [  0,   0,   0],
       [  6, -12,   6]])

In [ ]:
np.add(a,b) # add of two matrix

array([[10, 10, 10],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [70]:
np.diagonal(a)

array([1, 5, 9])

In [71]:
np.diagonal(b)

array([9, 5, 3])

create a 6*6 matrix by using atraange fun  and find eigen value eigen vector , rank ,determanant in diagonalof the element 

In [77]:
s=np.linspace(1,60,num=36,dtype=int).reshape(6,6)
s,

(array([[ 1,  2,  4,  6,  7,  9],
        [11, 12, 14, 16, 17, 19],
        [21, 22, 24, 26, 27, 29],
        [31, 33, 34, 36, 38, 39],
        [41, 43, 44, 46, 48, 49],
        [51, 53, 54, 56, 58, 60]]),)

In [84]:
np.linalg.matrix_rank(s)

np.int64(4)

In [81]:
eigrn_value,eigen_vector=np.linalg.eig(s)
eigen_vector
eigon_value

array([ 1.58943146e+02, -3.94314650e+00, -9.02568202e-15,  4.95296857e-15,
        9.20545154e-15])

In [83]:
np.linalg.det(s)

np.float64(0.0)

In [82]:
np.diagonal(s)

array([ 1, 12, 24, 36, 48, 60])

In [ ]:
# vstack used in stack in vertically
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
# hstack used in stack in horizontally
np.hstack([a,b])

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [ ]:
# we can perform all mathematical  calcualation which could be apply on matrix

In [89]:
# broatcasting 
# a+5
b+6

array([[15, 14, 13],
       [10, 11, 12],
       [ 7,  8,  9]])

In [90]:
a-5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [91]:
a*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# point vaise multiplication 
a*b

array([[ 9, 16, 21],
       [16, 25, 36],
       [ 7, 16, 27]])

In [ ]:
# float division 
a/b

array([[0.11111111, 0.25      , 0.42857143],
       [1.        , 1.        , 1.        ],
       [7.        , 4.        , 3.        ]])

In [ ]:
# Floar division
a//b


array([[0, 0, 0],
       [1, 1, 1],
       [7, 4, 3]])

Matrix multiplication
Write a NumPy function to perform matrix multiplication on two given matrices.

In [ ]:
x=np.linspace(5,5,dtype=int)

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [15]:
a*b

array([ 4, 10, 18])

In [16]:
np.dot(a,b)

np.int64(32)

In [21]:
c=np.array([[3,4,],[7,8]])
d=np.array([[4,5],[6,7]])

In [22]:
c*d

array([[12, 20],
       [42, 56]])

In [23]:
np.dot(c,d)

array([[36, 43],
       [76, 91]])

2. Array reshaping
Reshape a given 1D array into a 2D array with a specified number of rows and columns

In [ ]:
x=np.linspace(12,30,num=16,dtype=np.float32).reshape(4,4)
x,

(array([[12. , 13.2, 14.4, 15.6],
        [16.8, 18. , 19.2, 20.4],
        [21.6, 22.8, 24. , 25.2],
        [26.4, 27.6, 28.8, 30. ]], dtype=float32),)

In [39]:
x[3,3]

np.float32(30.0)

In [40]:
y=x[1:3,1:3]

In [46]:
y.shape

(2, 2)

10. Array manipulation
Use NumPy functions to flip, rotate, and transpose a given array

In [98]:
a=np.linspace(4,20,num=16,dtype=int).reshape(4,4)
a,
print(np.flip(a))

[[20 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]]


In [99]:
np.rot90(a)

array([[ 7, 11, 15, 20],
       [ 6, 10, 14, 18],
       [ 5,  9, 13, 17],
       [ 4,  8, 12, 16]])

In [100]:
np.transpose(a)

array([[ 4,  8, 12, 16],
       [ 5,  9, 13, 17],
       [ 6, 10, 14, 18],
       [ 7, 11, 15, 20]])

8. Array concatenation
Concatenate two or more arrays along a specified axis using NumPy

In [91]:
a=np.linspace(12,30,num=4,dtype=int).reshape(2,2)
b=np.linspace(12,50,num=4,dtype=int).reshape(2,2)
a

array([[12, 18],
       [24, 30]])

In [93]:
np.vstack([a,b])

array([[12, 18],
       [24, 30],
       [12, 24],
       [37, 50]])

In [94]:
np.half([a,b])

array([[[12., 18.],
        [24., 30.]],

       [[12., 24.],
        [37., 50.]]], dtype=float16)

6. Random number generation
Generate a specified number of random numbers from a normal distribution using NumPy

In [68]:
np.random.random()

0.41306460584489013

In [69]:
np.random.random(size=(2,2))

array([[0.25357414, 0.57896687],
       [0.38189787, 0.13076302]])

In [73]:
np.random.random(size=(3,3))

array([[0.04606182, 0.19138251, 0.09685218],
       [0.62842831, 0.34163592, 0.03514515],
       [0.15729719, 0.79932888, 0.61413132]])

In [79]:
np.random.normal(2,3,)

3.699711000760618

In [86]:
np.random.normal(2,3,size=(2,3))

array([[ 0.64470667,  2.37708005,  0.82629675],
       [-2.27062936,  0.10551512,  2.2131783 ]])

In [87]:
np.random.randint(5,8)

5

9. Statistical operations
Calculate the mean, median, and standard deviation of a given array using NumPy

In [76]:
x=np.linspace(12,30,num=16,dtype=int).reshape(4,4)
y=np.linspace(1,30,num=16,dtype=int).reshape(4,4)
x+y



array([[13, 15, 18, 21],
       [24, 28, 31, 34],
       [37, 40, 44, 47],
       [50, 53, 56, 60]])

In [83]:
np.mean(x)

np.float64(20.625)

In [84]:
np.median(x)

np.float64(20.5)

In [85]:
np.std(x)

np.float64(5.498579361980693)

In [101]:
np.var(x)

np.float64(30.234375)

In [102]:
np.std(x)**2

np.float64(30.234375000000004)

In [103]:
np.amax(x)

np.int64(30)

In [104]:
np.amin(x)

np.int64(12)

In [4]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[4,5,6]])
a+b

array([[ 8, 10, 12],
       [ 8, 10, 12]])