In [ ]:
import numpy as np

In [21]:
np.sin(10)

np.float64(-0.5440211108893698)

In [22]:
np.cos(10)

np.float64(-0.8390715290764524)

In [23]:
np.tan(10)

np.float64(0.6483608274590866)

In [24]:
np.sin(10)**2+np.cos(10)**2

np.float64(1.0)

In [3]:
1+np.arccos(10)*((np.tan(10))**2)

C:\Users\HP\AppData\Local\Temp\ipykernel_5184\1191309413.py:1: RuntimeWarning: invalid value encountered in arccos
  1+np.arccos(10)*((np.tan(10))**2)


np.float64(nan)

Hyperlink sin function

In [25]:
np.sinh(12)

np.float64(81377.39570642986)

In [8]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a.ndim

2

In [10]:
a[2]

array([7, 8, 9])

In [14]:
a[1:2,1:2]

array([[5]])

In [13]:
a[:,1]

array([2, 5, 8])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a[1,2]

np.int64(6)

In [18]:
a[1,1]

np.int64(5)

In [19]:
a[2,1]

np.int64(8)

In [26]:
a>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [28]:
b=np.linspace(12,40,num=16,dtype=int).reshape(4,4)
b

array([[12, 13, 15, 17],
       [19, 21, 23, 25],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [29]:
b[(b>15) & (b<38)]

array([17, 19, 21, 23, 25, 26, 28, 30, 32, 34, 36])

In [36]:
b.T

array([[12, 19, 26, 34],
       [13, 21, 28, 36],
       [15, 23, 30, 38],
       [17, 25, 32, 40]])

In [72]:
b[1]=b[2]
b

array([[12, 13, 15, 34],
       [26, 28, 30, 32],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [57]:
arr=np.tile(np.arange(5),(5,1))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [56]:
arr[:,[0,2]]=arr[:,[2,0]]
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [53]:
arr


array([[2, 1, 0, 3, 4],
       [2, 1, 0, 3, 4],
       [2, 1, 0, 3, 4],
       [2, 1, 0, 3, 4],
       [2, 1, 0, 3, 4]])

In [67]:
b

array([[12, 13, 15, 34],
       [19, 21, 23, 25],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [73]:
np.linalg.det(b)

np.float64(0.0)

In [74]:
np.linalg.eigvals(b)

array([ 1.16429465e+02, -7.42843736e+00,  9.98972135e-01,  4.97141213e-15])

In [75]:
np.linalg.eig(b)

EigResult(eigenvalues=array([ 1.16429465e+02, -7.42843736e+00,  9.98972135e-01,  4.97141213e-15]), eigenvectors=array([[-0.33761325, -0.89618448,  0.80828878,  0.39249353],
       [-0.4949233 ,  0.17692766, -0.41263783, -0.80807492],
       [-0.4949233 ,  0.17692766, -0.41263783,  0.43866924],
       [-0.62937997,  0.36639675,  0.07828976, -0.02308785]]))

In [ ]:
egn_value, 

In [1]:
import numpy as np