--> work
1.BASIC ARRAY CREATION
2.ARRAY GENERATION FUN
3.RANDOM GENERATION FUN
4.ARRAY ATTRIBUTES
5.ARRAY METHOD

In [271]:
import numpy as np

In [272]:
# BASIC ARAY CREATION
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [273]:
a=np.array([4,5,7,8])
a

array([4, 5, 7, 8])

In [274]:
a=[[1,2,4],[4,5,6],[4,5,6]]


In [275]:
arr=np.array(a)
arr

array([[1, 2, 4],
       [4, 5, 6],
       [4, 5, 6]])

In [276]:
a=[[1,2],[4,5],[3,7]]

In [277]:
np.array(a)

array([[1, 2],
       [4, 5],
       [3, 7]])

In [278]:
arr

array([[1, 2, 4],
       [4, 5, 6],
       [4, 5, 6]])

In [279]:
a=[1,2,3,4,5,3.5,'']
a

[1, 2, 3, 4, 5, 3.5, '']

In [280]:
np.array(a)
# u32 means all the data type to convet a str kuka atring string are work for a same data type

array(['1', '2', '3', '4', '5', '3.5', ''], dtype='<U32')

In [281]:
a=[[1,2,3],[4,5,4]]
a
# list are not support a multidimentioanl

[[1, 2, 3], [4, 5, 4]]

In [282]:
s=np.array(a)
s

array([[1, 2, 3],
       [4, 5, 4]])

In [283]:
s=np.array([[1,2,3],[4,5,6],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

Array genetation  function

In [284]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [285]:
s=np.arange(1,17)
s


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [286]:
a=np.zeros([5,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [287]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [288]:
np.linspace(1,5,12)

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [289]:
# linspace = return evenly spaced num oveer a specified interval
arr=np.linspace(1,5,10) 
arr 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation function

In [290]:
np.random.rand(10)

array([0.71920611, 0.87983511, 0.00693152, 0.40705705, 0.31010557,
       0.18178945, 0.38942982, 0.35749366, 0.38836701, 0.50931045])

In [291]:
# value jub 0 to 1 ka bich aati ha to usha normalization kaitha ha 
# or jun -3 to 3 ta k aati ha to usha standardization khata ha
np.random.randn(10)

array([ 0.10440431, -0.50015932,  0.91043075, -0.74176198, -1.4273196 ,
       -0.51167918, -1.16285189, -0.94325892,  0.14708441, -0.93042945])

In [292]:
np.random.randint(10,20,10)

array([12, 12, 18, 10, 16, 14, 17, 19, 11, 13], dtype=int32)

Array Attributes

In [293]:
# Attributes ko likha nahi jata ha
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [294]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [295]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape
arr.size
arr.min()
arr.max()
arr.std()

np.float64(2.581988897471611)

In [296]:
arr.shape
arr.max()
arr.min()
arr.mean()
arr.std()

np.float64(2.581988897471611)

In [297]:
arr.shape

(3, 3)

In [298]:
arr.size

9

In [299]:
arr.dtype

dtype('int64')

Array Method

In [300]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [301]:
arr.min()

np.int64(1)

In [302]:
arr.max()

np.int64(9)

In [303]:
arr.sum()

np.int64(45)

In [304]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [305]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [306]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [307]:
np.sum(arr,1)

array([ 6, 15, 24])

In [308]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [309]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [310]:
# column vise sum hona to axis=0
np.sum(arr,axis=0)

array([12, 15, 18])

In [311]:
# row wise
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [312]:
# middle value is mean
arr.mean()

np.float64(5.0)

In [313]:
arr.std()

np.float64(2.581988897471611)

In [314]:
arr.argmax()
# mean a max value ka index value 

np.int64(8)

In [315]:
arr.argmin()

np.int64(0)

Reshape & Resizing

In [316]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [317]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [318]:
# resize mean ha ja name sa create kiya tha ushi name sa save kar do
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

--> numpy indexing
numpy indexing and slicing of vector 
numpy indexing and slicing of matrix
boolean matrix



In [319]:
import numpy as np

numpy indexing and slicing of vector 

In [320]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [321]:
ar=np.arange(21,31)
ar

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [322]:
ar[7]

np.int64(28)

In [323]:
s=np.arange(5,35).reshape(5,6)
s

array([[ 5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [324]:
ar[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [325]:
# indexing
arr[9]

np.int64(20)

In [326]:
# slicing
arr[1:5]

array([12, 13, 14, 15])

In [327]:
arr[3::2]

array([14, 16, 18, 20])

In [328]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

numpy indexing and slicing of matrix

In [329]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [330]:
arr[0:3,:]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [331]:
arr[2:,:]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [332]:
arr[0:3,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [333]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [334]:
arr[2:,3:]

array([[16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])

In [335]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [336]:
# rows
arr[1]

array([ 6,  7,  8,  9, 10])

In [337]:
# column
arr[0,0]

np.int64(1)

In [338]:
arr[5,4]

np.int64(30)

In [339]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [340]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [341]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [342]:
arr[1:3,:4]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

Boolean indexing

In [343]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [344]:
n=np.arange(11,19)
n

array([11, 12, 13, 14, 15, 16, 17, 18])

In [345]:
n1=n%2==0
n1
n1.sum()

np.int64(4)

In [346]:
n=n[n1]
n

array([12, 14, 16, 18])

In [347]:
s=arr%2==0
s

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [348]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [349]:
# one time execute a line a num of items a lees to errror to a rerun a run the code
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

-->ARRAY OPEERATION

1.Arthmetic operation
2.boadcasting
3.Deep and shello copy
4.Matrix operation
5.Advance array manipulation
6.Stacking array
7.Spliting array

In [350]:
import numpy as np

1.Arthmetic operation

In [351]:
a=np.array([1,2,3])
b=np.array([7,8,9])
a
b
a+b
a*b
a/b
a//b
a-b

array([-6, -6, -6])

In [352]:
# array size are same 
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a
b

array([ 6,  7,  8,  9, 10])

In [353]:
a+b

array([ 7,  9, 11, 13, 15])

In [354]:
a-b

array([-5, -5, -5, -5, -5])

In [355]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [356]:
a//b

array([0, 0, 0, 0, 0])

In [357]:
a%b

array([1, 2, 3, 4, 5])

In [358]:
a**b

array([      1,     128,    6561,  262144, 9765625])

2.boadcasting

In [359]:
s=np.arange(1,31).reshape(5,6)
s+10
a*10

array([10, 20, 30, 40, 50])

In [360]:
l=[10,20,30,40]
arr=np.array(l)

In [361]:
arr+10

array([20, 30, 40, 50])

In [362]:
arr=np.arange(1,26).reshape(5,5)
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [363]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [364]:
s=[1,4,5,7]
arr=np.array(s)
arr

array([1, 4, 5, 7])

In [365]:
arr=np.arange(1,26).reshape(5,5)
arr
arr*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [366]:
arr*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

3.Deep and shallow copy

In [367]:
s=np.arange(1,21)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [368]:
n=s
n*5
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [369]:
# shallo copy 
a=[[1,2],[3,4]]
a
shallow=a.copy()
a[0][1]=10
a
shallow

[[1, 10], [3, 4]]

In [370]:
# deep copy
s=[[1,2],[3,4]]
deep=copy.deepcopy(s)
s[1][1]=50
print(s)
print(deep)

NameError: name 'copy' is not defined

In [ ]:
# shellow copy ma agar array ka andar koi bhi change karonga aap to koi bhi change  honga
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice=slice *10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a=[[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [ ]:
shallow=a.copy()
a[0][0]=100
a
shallow

[[100, 2], [3, 4]]

In [ ]:
a=[[1,2],[3,4]]
a
deep =a.d

AttributeError: 'list' object has no attribute 'd'

In [ ]:
# array a new location a and new space a ram
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[4:6]*5

array([25, 30])

In [ ]:
# slicing ka andaar koi change nahi honga mugar 
# hole index copy karta ha to usko kisi ma bhi store karka change karta ha to change honga
a
b=a
b[0]=99
b
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operation

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[5,9]])
a


array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[7, 8],
       [5, 9]])

In [ ]:
a@b

array([[17, 26],
       [41, 60]])

In [ ]:
np.dot(a,b)

array([[17, 26],
       [41, 60]])

In [ ]:
# transpose a convert a cor become acolumn and column become a row
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
b

array([[7, 8],
       [5, 9]])

In [ ]:
b.T

array([[7, 5],
       [8, 9]])

5.Advance array manipulation

stacking array

In [ ]:
# you can not stack with  matrix
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])


In [ ]:
# there are three type of stack  
# 1.vertical stack  2. horizontal stack 3.column stack
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

6. splitting array

In [ ]:
s=np.arange(9).reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.hsplit(s,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [ ]:
np.vsplit(s,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# split are two type horizontal split or vertical split
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

EXERCISE

In [ ]:
import numpy as np

valid sudoku

In [ ]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
        
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    ])

In [ ]:
s=np.sum(s,axis=1)
s==45
s

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("Sudhoko is not valid")
        break
else:
    print("Sudhoko is valid")

Sudhoko is not valid


In [ ]:
b=np.sum(s,axis=0)
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("sudoku is  valid")

sudoku is  valid


In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
s[0:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [ ]:
s[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
np.sum(s)

np.int64(405)

General Question

In [373]:
import numpy as np

# Columns : [Age,Maths Marks,Science Marks]
data=np.array([
    [12,58,96],
    [45,78,96],
    [78,56,25]
])

In [374]:
data

array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

In [375]:
# get the shape of matrix
data.shape

(3, 3)

# Que 1.Avarage age of student mean means a avarage

In [376]:
# Avarage age of student mean means a avarage
np.mean(data[:,0])

np.float64(45.0)

In [ ]:
mean=np.mean(data[:,0])
mean


np.float64(45.0)

In [ ]:
data

array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

In [377]:
# Avarage age of student
# or 
s=data[:,0]
s
np.average(s)

np.float64(45.0)

In [ ]:
data

array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

Que 2.Extract maths marks of all srudent

In [378]:
s=data[:,1]
s
np.sum(s)

np.int64(192)

Que 3.find the highest science marks

In [379]:
# Columns : [Age,Maths Marks,Science Marks]
data


array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

In [380]:
np.max(data[:,2])

np.int64(96)

QUe 4 get detail of the student who score more than 90 in maths 

In [381]:
data

array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

In [382]:
s=data[data[:,1] > 60]
s

array([[45, 78, 96]])

Increase maths marks of all student  by 5

In [383]:
data

array([[12, 58, 96],
       [45, 78, 96],
       [78, 56, 25]])

In [389]:
s=data[:,1]+5
s

array([63, 83, 61])

finfdhow many student are younger than 19


array([], shape=(0, 3), dtype=int64)

In [397]:
s=data[:,0]
s

array([12, 45, 78])

In [398]:
a=s>19
a

array([False,  True,  True])

In [400]:
s=s[a]
s

array([45, 78])

In [401]:
len(s)

2

In [ ]:
len(data[data[:,0] <19])

1

calculate the avg marks in each sunject

In [404]:
s=data[:,1:]
s
np.average(s)

np.float64(68.16666666666667)

In [ ]:
np.mean(data[:,1:],axis=0)

array([69.        , 72.33333333])

In [ ]:
# data of student  who scored at least 90in both sub 
data

array([[12, 63, 96],
       [45, 83, 96],
       [78, 61, 25]])

In [ ]:
data[(data[:,1] >=60) & (data[::,2] >=60)]

array([[12, 63, 96],
       [45, 83, 96]])

In [ ]:
# replace all science marks <75  with 0
data

array([[12, 63, 96],
       [45, 83, 96],
       [78, 61, 25]])

In [ ]:
data[:,2][data[:,2] <65]=0
data

array([[12, 63, 96],
       [45, 83, 96],
       [78, 61,  0]])

numpy que 

1.	Matrix multiplication 
Write a NumPy function to perform matrix multiplication on two given matrices


In [ ]:
import numpy as np

In [421]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a@b





array([[19, 22],
       [43, 50]])

In [ ]:
c=np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

In [426]:
a=np.array([[1,3,4],[7,8,9],[4,5,7]])
b=np.array([[1,4,7],[6,9,3],[6,8,7]])
a@b

array([[ 43,  63,  44],
       [109, 172, 136],
       [ 76, 117,  92]])

2.	Array reshaping 
Reshape a given 1D array into a 2D array with a specified number of rows and columns. 


In [ ]:
s=np.array([1,2,3,4,5,6]).reshape(2,3)
s

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
s=np.array([1,2,3,4,6,7]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [6, 7]])

In [ ]:
s=np.arange(1,17).reshape(4,4)
s


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

3.	Array indexing 
Use advanced indexing to select specific elements from a 2D array. 


In [ ]:
s=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
s




array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [430]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [433]:
a[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
s[1,1]


np.int64(5)

4.	Broadcasting 
Use broadcasting to perform element-wise operations on two arrays with different shapes. 


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [ ]:
a+b

array([[11, 22, 33, 44],
       [15, 26, 37, 48]])

In [461]:
a=np.array([[1,2,3,4],[4,5,4,6]])
a
b=np.arange(1,5)
b
a+b


array([[ 2,  4,  6,  8],
       [ 5,  7,  7, 10]])

6.	Random number generation 
Generate a specified number of random numbers from a normal distribution using NumPy. 


In [ ]:
s=np.random.rand(1,10)
s

array([[0.19773374, 0.14506323, 0.99460376, 0.98607017, 0.88456583,
        0.96822686, 0.59882605, 0.42135027, 0.05871393, 0.65567768]])

 
7.	Array sorting 
Sort a 2D array along a specified axis using NumPy. 


In [ ]:
s=np.array([[1,2,3,4],[5,6,7,8]])
x=np.sum(s,axis=0)
x

array([ 6,  8, 10, 12])

8.	Array concatenation 
Concatenate two or more arrays along a specified axis using NumPy. 


In [ ]:
a=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
b=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a=np.arange(1,9).reshape(2,4)
b=np.arange(22,30).reshape(2,4)


array([[22, 23, 24, 25],
       [26, 27, 28, 29]])

In [ ]:
c=np.sum([a,b],axis=0)
c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

9.	Statistical operations 
Calculate the mean, median, and standard deviation of a given array using NumPy. 


In [488]:
s=np.arange(1,21).reshape(4,5)
np.mean(s)
np.median(s)
np.std(s)
np.max(s)
np.min(s)

np.int64(1)

In [ ]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
s=np.mean(a)
s

np.float64(10.5)

In [ ]:
s=np.median(a)
s

np.float64(10.5)

In [ ]:
s=np.std(a)
s

np.float64(5.766281297335398)

10.	Array manipulation 
Use NumPy functions to flip, rotate, and transpose a given array. 


In [491]:
a=np.arange(1,21).reshape(4,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [496]:
np.flip(a)
np.rot90(a)
np.transpose(a)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [ ]:
x=np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
s=np.flip(x)
s

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
s=np.rot90(s)
s

array([[16, 11,  6,  1],
       [17, 12,  7,  2],
       [18, 13,  8,  3],
       [19, 14,  9,  4],
       [20, 15, 10,  5]])

s=np.arange(1,17).reshape(4,4)
s
# fancindexing
s[[0,3]]
# booleanindexing
s>10
s.shape
s[s>10]
# ravel fun to convert a 2d ya 30 any type to convet a  1 d array 
np.ravel(s)
arr=np.arange(1,10)
arr
np.cumsum(arr)
np.cumprod(arr)
arr.shape
a=np.expand_dims(arr,axis=0)
a.shape