I. Create a 4x4 matrix representing a game board with values ran
ging from 0 to 15. Extract and print the bottom-right 2x2 subboard.

In [1]:
import numpy as np

In [2]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
arr=np.arange(0,16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
arr[2:4,2:4]

array([[10, 11],
       [14, 15]])

II. Generate an array with 20 random integers between 10 and 50.
Slice out every alternate element starting from the second ele
ment and print the result.

In [5]:
arr=np.random.randint(10.50,size=20)
arr

array([7, 6, 9, 4, 2, 9, 1, 7, 0, 4, 4, 2, 8, 6, 8, 7, 0, 8, 2, 5],
      dtype=int32)

In [6]:
arr[1:2]

array([6], dtype=int32)

III. Create a 4x4 matrix with elements range between 16 to 31.
Extract and print the middle 2x2 sub-matrix.

In [7]:
s=np.arange(16,32).reshape(4,4)
s
s[1:3,1:3]

array([[21, 22],
       [25, 26]])

In [8]:
arr=np.arange(16,32).reshape(4,4)
arr

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
arr[1:3,1:3]

array([[21, 22],
       [25, 26]])

IV. 3D array representing RGB colour channels of a 2x3 image. Slice
and print the green channel (second channel).

In [10]:
s=np.random.randint(0,100,size=(3,3,3))
s

array([[[ 5, 53, 37],
        [56,  2, 57],
        [65, 34, 31]],

       [[95, 71, 16],
        [27,  7, 17],
        [31, 36, 33]],

       [[48, 17, 46],
        [24, 33, 63],
        [42, 42, 28]]], dtype=int32)

In [11]:
s[:,:,0]

array([[ 5, 56, 65],
       [95, 27, 31],
       [48, 24, 42]], dtype=int32)

In [12]:
arr=np.array([[[1,2],[3,4],[6,5]],[[7,8],[6,4],[3,2]],[[7,8],[6,1],[6,7]]])
arr

array([[[1, 2],
        [3, 4],
        [6, 5]],

       [[7, 8],
        [6, 4],
        [3, 2]],

       [[7, 8],
        [6, 1],
        [6, 7]]])

In [13]:
arr.shape

(3, 3, 2)

In [14]:
arr

array([[[1, 2],
        [3, 4],
        [6, 5]],

       [[7, 8],
        [6, 4],
        [3, 2]],

       [[7, 8],
        [6, 1],
        [6, 7]]])

In [15]:
arr[:,:,1]

array([[2, 4, 5],
       [8, 4, 2],
       [8, 1, 7]])

In [16]:
arr.shape

(3, 3, 2)

In [17]:
green_channel=arr[:,:,1]
green_channel

array([[2, 4, 5],
       [8, 4, 2],
       [8, 1, 7]])

In [18]:
arr[:,:,1]

array([[2, 4, 5],
       [8, 4, 2],
       [8, 1, 7]])

V. Create a 4x4x4 array of random elements. Extract and print a
2x2x2 sub-array from the centre of the array.

In [19]:
arr=np.random.randint(0,100,size=(4,4,4))
arr

array([[[22,  3, 13, 38],
        [81, 35, 98, 12],
        [93, 97, 29, 52],
        [49, 33,  4,  8]],

       [[12, 47, 71, 68],
        [66, 22, 25, 74],
        [12, 61, 25,  5],
        [90, 18, 60, 49]],

       [[39, 25, 69, 88],
        [92, 55, 30, 65],
        [47, 14, 18,  1],
        [69, 37, 58, 54]],

       [[86, 99, 82, 94],
        [74, 34, 28, 51],
        [89, 22, 56, 21],
        [42, 44, 65, 85]]], dtype=int32)

In [20]:
arr[1:3,1:3,1:3]

array([[[22, 25],
        [61, 25]],

       [[55, 30],
        [14, 18]]], dtype=int32)

In [21]:
s=np.random.randint(1,100,size=[4,4,4])
s[1:3,1:3,1:3]

array([[[98, 80],
        [21,  5]],

       [[12, 32],
        [91, 10]]], dtype=int32)

VI. Write a program which replace odd elements 2D array with -1.


In [22]:
s=np.arange(1,21).reshape(4,5)
s[s%2!=0] =-1
s

array([[-1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1],
       [16, -1, 18, -1, 20]])

In [23]:
arr=np.arange(11,20).reshape(3,3)
arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
arr[arr%2 !=0] = -1
arr

array([[-1, 12, -1],
       [14, -1, 16],
       [-1, 18, -1]])

VII. You have a 7x7 grid representing scoreboard. Print the values o
f the main diagonal (from top-left to bottom-right).


In [25]:
arr=np.random.randint(1,100,size=(7,7))
arr

array([[27, 72,  4, 14,  3, 29, 55],
       [87, 90, 39, 16, 60, 70, 40],
       [61, 91, 10, 17, 16, 17,  1],
       [44, 81, 14, 57, 53, 38,  3],
       [69, 78, 11,  2, 98, 99, 90],
       [69, 70, 35, 59, 75,  6, 54],
       [59, 17, 43, 91, 80, 18,  8]], dtype=int32)

In [26]:
np.diag(arr)

array([27, 90, 10, 57, 98,  6,  8], dtype=int32)

In [27]:
a=np.random.randint(1,100,size=(7,7))
np.diag(a)

array([40, 31, 94, 50, 53, 43, 93], dtype=int32)

VIII. Ask user to input two numbers a, b. Write a program to
generate a random array of shape (a, b) and print the array and
average of the array.

In [28]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

arr=np.stack((a,b),axis=0)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
avarage=np.mean(arr)
avarage

np.float64(5.5)

IX. Write a program to Create a null vector of size 10 but the fifth
value which is 1.

In [30]:
arr=np.zeros(11)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
arr[4] =1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

X. Write a program to create a 5x5 matrix with row values ranging
from 0 to 4.


In [39]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [47]:
# tile are use in repeat in num 
np.tile(np.arange(2,7),(5,1))

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [33]:
np.tile(np.arange(6),(1,6))

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
        4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

In [34]:
arr= np.tile(np.arange(5),(5,1))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [35]:
arr.max()

np.int64(4)

In [36]:
arr.min()

np.int64(0)

XI. Write a program which Swap first column of array with second
column in the array of 3x3 matrix

In [37]:
arr=np.random.randint(0,10,size=(3,3))
arr

array([[4, 7, 2],
       [6, 3, 0],
       [4, 5, 5]], dtype=int32)

In [53]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)



[[7 4 2]
 [3 6 0]
 [5 4 5]]


IMPORTANT TOPIC

1.analize the business model
2.Data Collection
3.Data Cleaning ->
Check Data pype and  all column Cleck duplicate value ccheck outlier  if data has a categorical data  r remove the whide space convert to the same space 

-> Null value treatment
-> outlier treatement
-> Duplicarte value treatment

4..EDA (Explotary Data Analysis)
->1. univarate analysis 
2.bivariate analysis
3.multivariate analysis
4.

5.Model Deployment
6.Automation and Testing


