Numpy liberary Assignment 2

Q1. Write a program which Subtract the mean of each row from a
matrix. (Create a matrix of random elements)


In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,17,size=(4,4))
arr

array([[ 9,  6, 14,  9],
       [ 9,  4, 16,  1],
       [ 3, 11, 13,  7],
       [10,  7,  4, 10]], dtype=int32)

In [4]:
m=arr.mean()
m

np.float64(8.3125)

In [5]:
s1=arr-m
s1

array([[ 0.6875, -2.3125,  5.6875,  0.6875],
       [ 0.6875, -4.3125,  7.6875, -7.3125],
       [-5.3125,  2.6875,  4.6875, -1.3125],
       [ 1.6875, -1.3125, -4.3125,  1.6875]])

Q2. Write a python program to count the number of elements in 2D
array.
Test case:
Input: np.array([1, 2])
Expected Output: 2


In [6]:
arr=np.array([1,2])
arr

array([1, 2])

In [7]:
count=arr.size
count

2

Q3. You are given a space separated list of numbers. Your task is to
print a reversed NumPy array with the element type float.
Test Case:
Input: 1 2 3 4 5 6 7 8
Expected Output: [8.0 7.0 6.0 5.0 4.0 3.0 2.0 1.0]


In [8]:
arr=np.array([1,2,3,4,5,6,7,8],dtype=float)
arr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [9]:
arr[::-1]

array([8., 7., 6., 5., 4., 3., 2., 1.])

Q4. Create the following pattern without hardcoding. Use only
numpy functions and the below input array a.
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [10]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
a1=np.repeat(a,3)
a1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
a2=np.tile(a,3)
a2

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
add=np.concatenate([a1,a2])
add

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q5. Write a function to create a 2d array with 1 on the border and 0
inside. Take 2-D array shape as (a, b) as parameter to function.
Input: a = 4
 b = 4
Expected Output:
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]

In [14]:
a=4
b=4
arr=np.ones((a,b),dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
arr[1:-1,1:-1] =0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Q6. Write a function which will accept 2 arguments.
First: A 1D numpy array arr
Second: An integer n {Please make sure n<=len(arr)}
Output: The output should be the nth largest item out of the array.
Test Case:
Input: arr = (12,34,40,7,1,0) and n=3,
Output; 12
Test case:
Input: arr=(12,34,40,7,1,0) and n=1
Output: 40

In [3]:

def aray(arr,n):
    if n> len(arr):
        raise ValueError("n should be less than or equal to the length of arr")
    
    sorted_arr=np.sort(arr)[::-1]
    return sorted_arr[n-1]

arr=np.array([10,20,5,8,70])
n=2
print("The largest num is ",aray(arr,n))

The largest num is  20


 
Q7. Write a program which makes an array having corresponding max value out of two given arrays. 
Input:  
a=np.array([6,3,1,5,8]) b=np.array([3,2,1,7,2]) 
Output: [6 3 1 7 8] 


In [6]:
import numpy as np

    

In [21]:


a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])
s = []

for i in range(len(b)):
    if a[i] < b[i]:
        s.append(int(b[i]))  # convert to Python int
    else:
        s.append(int(a[i]))

s



[6, 3, 1, 7, 8]

In [10]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
s=np.maximum(a,b)
s

array([6, 3, 1, 7, 8])

Q8. Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error. 
Test Case: 
 	Input: a= [[0 1 2 3 4][5 6 7 8 9]]  	 	  
    b= [[1 1 1 1 1][1 1 1 1 1]] 
Output: [[0 1 2 3 4] 
        [5 6 7 8 9] 
        [1 1 1 1 1] 
        [1 1 1 1 1]] 


In [39]:
def vertical_stack(*arrays):
    for arr in arrays:
        if not isinstance(arr,np.ndarray):
            raise TypeError('All input ust be numpy array')
    return np.vstack(arrays)
a=np.array([[0,1,2,3,4],[5,6,7,8,9]]) 	 	  
b=np.array([[1,1,1,1,1],[1,1,1,1,1]])

result=vertical_stack(a,b)
result

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])